### ISSUE TITLE
您好，可以帮忙升级一下amis和amis-editor版本么，新版本有很多组件，旧版本上没有

### ISSUE THREAD

**Issue by liuli01** [giscafer/sailor#4]

**Comment by giscafer** [comment]
有 breaking changed?，没有的话按理自己 npm install 最新版本就可以了吧

**Comment by liuli01** [comment]
Npm install amis@最新版本 和amis-editor @最新版本 后，报错
前端页面什么也不显示，出现的报错，无法修复，希望大神有时间帮忙更新一下，谢谢
***@***.***


从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: Nickbing ***@***.***>
发送时间: 2022年9月20日 20:12
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [giscafer/sailor] 您好，可以帮忙升级一下amis和amis-editor版本么，新版本有很多组件，旧版本上没有 (Issue #4)


有 breaking changed?，没有的话按理自己 npm install 最新版本就可以了吧

―
